ng g c components/nested-routes-demo/home
ng g c components/nested-routes-demo/java
ng g c components/nested-routes-demo/java/core-java
ng g c components/nested-routes-demo/java/javaee
ng g c components/nested-routes-demo/java/spring
ng g c components/nested-routes-demo/angular
ng g c components/nested-routes-demo/angular/angularjs
ng g c components/nested-routes-demo/angular/angular7
ng g c components/nested-routes-demo/node
